// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from injector.go:

func initializeX() X {
	a := NewA()
	b := NewB(a)
	i2 := _wireCValue
	d := NewD(i2)
	mainE := _wireEValue
	h := NewH(a, mainE)
	g := h.G
	x := NewX(b, d, g)
	return x
}

var (
	_wireCValue = c
	_wireEValue = e
)
